Axllent\Intelligent404\Intelligent404:
  allow_in_dev_mode: false            # allow this to work in dev mode
  redirect_on_single_match: true      # auto-redirect if only one exact match is found
  data_objects:
    \SilverStripe\CMS\Model\SiteTree:
      group: Pages                    # The ArrayList to be supplied to the template
      filter: []                      # $do->get()->filter($where)
      exclude:                        # $do->get()->exclude($exclude)
        ClassName:
          - SilverStripe\CMS\Model\ErrorPage
          - SilverStripe\CMS\Model\RedirectorPage
          - SilverStripe\CMS\Model\VirtualPage
